test_size: 0.2
random_state: 42
batch_size: 32
seed: 128
image_size: [256, 256]
conv_first_layer: 32
conv_sec_layer: 64
conv_third_layer: 128
conv_fourth_layer: 256
kernel_size: [3, 3]
input_shape: [256, 256, 3]
pool_size: [2, 2]
strides: 2
dropout_rate: 0.25
dense_first_layer: 128
dense_second_layer: 64
output_layer: 1
l2_regularization: 0.01
optimizer: adam
loss: binary_crossentropy
epochs: 1