artifacts_folder: artifacts

downloading_data:
  source_dir: artifacts/raw_data
  source_URL: karakaggle/kaggle-cat-vs-dog-dataset

preproccessed_data:
  datasets_dir: artifacts/datasets
  train_dir: artifacts/datasets/train
  test_dir: artifacts/datasets/test

image_categories:
  - train/Dog
  - train/Cat
  - test/Dog
  - test/Cat