name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Login to Heroku
      env:
        HEROKU_API_KEY: HRKU-824d6b1c-7f8c-4a3c-b4b3-d2e3703bc4c4
      run: heroku auth:token

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: HRKU-824d6b1c-7f8c-4a3c-b4b3-d2e3703bc4c4
      run: |
        git remote add heroku https://heroku:HRKU-824d6b1c-7f8c-4a3c-b4b3-d2e3703bc4c4@git.heroku.com/cnn.git
        git push heroku main
